name: Coverage

on: [push, pull_request]

jobs:

  run:
    name: Coverage
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@master

      - name: Install dependencies
        run: |
          cd client
          npm ci
          cd ../server
          npm ci
          cd ../

      - name: Run tests and collect coverage
        run: |
          cd client
          npm run test
          cd ../server
          npm run test
          cd ../

      - name: Upload coverage to codecov
        uses: codecov/codecov-action@v1.0.13

        with:
          files: ./server/coverage/coverage-final.json, ./client/coverage/coverage-final.json
          flags: unittest
